### PR TITLE
Add filter_by_regex parameter for regex support

### PR DESCRIPTION
**Pull request by annapowellsmith**
Add new filter_by_regex parameter. This is similar to the existing
filter_by parameter, except that it will pass a regular expression
query through to Mongo.

The Mongo query is also constructed using 'find', but passed through
as { 'pagePath': /housing-benefit/ } rather than { 'pagePath':
'/housing-benefit' }. Mongo will parse this as a regular expression
query.

We validate and compile the regular expressions using Python's
re module, and pass them to Mongo using pymongo - this should
handle the Python regex -> PCRE conversion for us.

The justification for this parameter is to support multi-part formats in
the info-frontend application - e.g. we would like to serve aggregate
statistics for the number of tickets submitted across all pages in multi-part
guides and smart answers. To do this with the existing filter_by
parameter would require a call to Backdrop for each page in the guide
or smart answer, and some of these formats have 30+ pages. This query
will make these calls a lot faster.

I have done some benchmarking on the speed of regex queries against
the page-statistics and page-contacts datasets, and it seems to be
acceptable. It is faster when regexes are anchored to the start of the
string. I haven't enforced anchoring here (we will do this in the
info-frontend query) but we could do this later if it becomes an issue.

### CODE REVIEW

**Comment by tombooth** [comment]
Looks good! The only comment would be that it looks like you can't have both a filter_by and a filter_by_regex parameter, could this be validated in `validate_request_args`?

**Comment by jabley** [comment]
I'm a bit nervous that this opens up a potential attack vector. [MongoDB uses PCRE](http://docs.mongodb.org/v2.4/reference/operator/query/regex/) but I don't know what the engine is (NFA or DFA) and thus whether it can be attacked via [pathological backtracking](http://swtch.com/~rsc/regexp/).

Are you able to reassure me that this isn't an issue I need to worry about?

**Comment by tombooth** [comment]
As mentioned in chat, it could be switch to a prefix match and we build the regex ourselves

**Comment by annapowellsmith** [comment]
We could use something like maxTimeMS globally to terminate slow running queries: http://docs.mongodb.org/manual/reference/method/cursor.maxTimeMS/ 

There might be other good reasons to use this too, particularly as the info statistics collections get larger and larger.

**Comment by annapowellsmith** [comment]
After a chat, we think it makes most sense to use a prefix filter rather than a regex, for now. I'll therefore close this pull request and redo the code.

**Pull request closed without merging**
