### PR TITLE
Create output dataset if missing using the api.

### PR DESCRIPTION
**Pull request by jcbashdown**
Default params are those of the parent. If it's realtime for instance
the transform target probably also needs to be realtime. The only
difference is the data_type and consequently the name (as this is auto
generated)

Relies on:

https://github.com/alphagov/performanceplatform-client.py/pull/43

### CODE REVIEW

**Comment by tombooth** [comment]
Does this need to be updated to use the newer client version?

**Comment by jcbashdown** [comment]
Whoops, yes.

**Comment by jcbashdown** [comment]
Whoops, yes.

On 14 January 2015 at 12:18, Tom Booth <notifications@github.com> wrote:

> Does this need to be updated to use the newer client version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alphagov/backdrop/pull/400#issuecomment-69908366>.
>



-- 
Jacob Ashdown
Developer: Performance Platform
Government Digital Service

Email: *jacob.ashdown@digital.cabinet-office.gov.uk
<jacob.ashdown@digital.cabinet-office.gov.uk>*

**Comment by jcbashdown** [comment]
@tombooth bumped.

**Pull request merged**
