### PR TITLE
Add Procfile worker

### PR DESCRIPTION
**Pull request by alexmuller**
This worker process will be used by GOV.UK Puppet when it spins up a worker to transform data.

### CODE REVIEW

**Comment by timmow** [comment]
The tests are failing on this, and are also failing on master when I rebuilt master - https://travis-ci.org/alphagov/backdrop/builds/60353517

Briefly looking at the test, I suspect an issue with dates, but not looked into in great detail yet

**Comment by mattrco** [comment]
Do we still need this? If so, I'm happy to rebase it against master, which is passing again.

**Comment by alexmuller** [comment]
Yep, thanks for the prompt! I've rebased against master and it's working now.

**Comment by mattrco** [comment]
:+1:

**Pull request merged**
